name: Update Spring Repo Secrets

on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@v3

      - name: Terraform Init + Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Extract Terraform Outputs
        id: tf_output
        run: |
          echo "ECR_URL=$(terraform output -raw repository_url)" >> $GITHUB_ENV
          echo "S3_BUCKET=$(terraform output -raw codedeploy_s3_bucket)" >> $GITHUB_ENV
          echo "CODEDEPLOY_APP=$(terraform output -raw codedeploy_app_name)" >> $GITHUB_ENV
          echo "CODEDEPLOY_GROUP=$(terraform output -raw codedeploy_group_name)" >> $GITHUB_ENV

      - name: Push Secrets to Spring Repo
        run: |
          gh secret set ECR_REGISTRY -b"$ECR_URL" --repo KTB-PERSONAL-PROJECT-RIVER/Backend
          gh secret set S3_BUCKET -b"$S3_BUCKET" --repo KTB-PERSONAL-PROJECT-RIVER/Backend
          gh secret set CODEDEPLOY_APP -b"$CODEDEPLOY_APP" --repo KTB-PERSONAL-PROJECT-RIVER/Backend
          gh secret set CODEDEPLOY_GROUP -b"$CODEDEPLOY_GROUP" --repo KTB-PERSONAL-PROJECT-RIVER/Backend
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # GitHub PAT
